# fly.toml app configuration file generated for muguntha-flights-lab on 2023-09-21T11:39:17-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "muguntha-flights-lab"
primary_region = "yul"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
